version: '3.8'
services:
  firebase:
    tty: true
    stdin_open: true
    container_name: firebase
    build:
      context: $PWD/services/firebase
      dockerfile: ./docker/Dockerfile
    restart: "no"
    network_mode: host
    ports: 
      - 4000:4000 # Emulator Suite UI
      - 8080:8080 # Cloud Firestore
      - 9099:9099 # Authentication
    env_file: $PWD/config/.firebase.env
    volumes:
      # Firestore data
      - $PWD/services/firebase/app/seed:/home/node/app/seed
    # entrypoint: ["firebase","emulators:start","--import=./seed","--export-on-exit"]
  frontend:
    container_name: frontend
    build:
      context: $PWD/services/frontend
      dockerfile: ./docker/Dockerfile
      args:
        user: "node"
        group: "node"
    restart: "no"
    network_mode: host
    ports: 
      # Nuxt default port
      - 3000:3000
      # Storybook
      - 3003:3003
    env_file: $PWD/config/.frontend.env
    volumes:
      - $PWD/services/frontend/app/src:/home/node/app/src
      - $PWD/docs:/home/node/app/dist
    # entrypoint: ["npm","run","dev"]